sudo: false
dist: trusty

cache:
  apt: true

env:
  global:
      - SPHINXBUILD=~/.local/bin/sphinx-build
      - DIFF_COMMIT=v0.5

git:
  depth: false

addons:
  apt:
    packages:
      - python-pip
      - latexmk
      - libalgorithm-diff-perl
      - texlive
      - texlive-latex-extra
      - texlive-humanities
      - texlive-generic-recommended
      - graphviz
      - texlive-generic-extra

install:
  - pip install --user mako
  - pip install --user Sphinx

before_script:
  - wget https://github.com/ftilmann/latexdiff/releases/download/1.2.1/latexdiff-1.2.1.tar.gz || wget http://mirror.tversu.ru/macports/distfiles/latexdiff/latexdiff-1.2.1.tar.gz
  - tar xvf latexdiff-1.2.1.tar.gz
  - export PATH=$PWD/latexdiff-1.2.1/:$PATH

script:
  - make latexpdf
  - make html
  - make singlehtml

before_deploy:
  - cp ./build/latex/ledge.pdf build/ledge-$TRAVIS_TAG.pdf
  - cp ./build/latex/ledge.pdf build/singlehtml/ledge-latest.pdf

deploy:
  - provider: releases
    prerelease: true
    api_key:
      secure: 
    file_glob: true
    file:
      - "build/ledge-*.pdf"
    skip_cleanup: true
    on:
      tags: true
      branch: master
  - provider: pages
    github_token: $GITHUB_TOKEN
    local_dir: "build/user-guide/singlehtml"
    skip_cleanup: true
    on:
      branch: master
